services:
  caddy:
    ports:
      - "${DESK_HTTP_BIND_ADDRESS:-0.0.0.0}:${DESK_HTTP_PORT:-80}:80"
      - "${DESK_HTTPS_BIND_ADDRESS:-0.0.0.0}:${DESK_HTTPS_PORT:-443}:443"
      - "${DESK_HTTPS_BIND_ADDRESS:-0.0.0.0}:${DESK_HTTPS_PORT:-443}:443/udp"

