/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exchangeDeviceSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDeviceDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDeviceConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProducts"];
        put?: never;
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get: operations["getProduct"];
        put?: never;
        post?: never;
        delete: operations["archiveProduct"];
        options?: never;
        head?: never;
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listServices"];
        put?: never;
        post: operations["createService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{serviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceId: components["parameters"]["ServiceId"];
            };
            cookie?: never;
        };
        get: operations["getService"];
        put?: never;
        post?: never;
        delete: operations["archiveService"];
        options?: never;
        head?: never;
        patch: operations["updateService"];
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAlerts"];
        put?: never;
        post: operations["createManualAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alertId}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acknowledgeAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alertId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDeployments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMarketQuotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWeather"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDevices"];
        put?: never;
        post: operations["createDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{deviceId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        get: operations["getDevice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateDevice"];
        trace?: never;
    };
    "/devices/{deviceId}/rotate-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateDeviceCredentials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProfiles"];
        put?: never;
        post: operations["createProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        get: operations["getProfile"];
        put: operations["replaceProfile"];
        post?: never;
        delete: operations["deleteProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/collectors/{collectorName}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryCollector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receiveGitHubWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/github/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receiveGitHubAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/uptime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receiveUptimeEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
            request_id: string;
            errors?: {
                [key: string]: string[];
            };
        };
        PublicHealth: {
            /** @enum {string} */
            status: "ok" | "degraded" | "unavailable";
            /** Format: date-time */
            checked_at: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded" | "unavailable";
            /** Format: date-time */
            checked_at: string;
            dependencies: {
                [key: string]: components["schemas"]["DependencyHealth"];
            };
        };
        DependencyHealth: {
            /** @enum {string} */
            status: "ok" | "degraded" | "unavailable";
            latency_ms?: number;
            detail?: string;
        };
        Version: {
            version: string;
            commit: string;
            /** Format: date-time */
            built_at: string;
            /** @constant */
            api_version: "v1";
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AccessTokenResponse: {
            access_token: string;
            /** @constant */
            token_type: "Bearer";
            /** @constant */
            expires_in: 900;
            user: components["schemas"]["User"];
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "admin" | "viewer";
            /** Format: date-time */
            created_at: string;
        };
        DeviceTokenRequest: {
            device_id: string;
            secret: string;
            firmware_version?: string;
        };
        DeviceTokenResponse: {
            access_token: string;
            /** @constant */
            token_type: "Bearer";
            /** @constant */
            expires_in: 900;
            mqtt: {
                /** Format: uri */
                url: string;
                client_id: string;
                username: string;
                /** @description Returned only when rotated or initially provisioned. */
                password?: string | null;
            };
        };
        Page: {
            items: unknown[];
            next_cursor?: string | null;
            has_more: boolean;
        };
        ProductWrite: {
            key?: string;
            name?: string;
            description?: string;
            enabled?: boolean;
        };
        Product: components["schemas"]["ProductWrite"] & {
            id: string;
            health: components["schemas"]["ServiceState"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Service: {
            id: string;
            product_id: string;
            key: string;
            name: string;
            status: components["schemas"]["ServiceState"];
            latency_ms?: number | null;
            /** Format: date-time */
            updated_at: string;
        };
        ServiceCreate: {
            product_id: string;
            key: string;
            name: string;
            kind?: string;
            /** Format: uri */
            endpoint?: string | null;
            /** @default true */
            enabled: boolean;
        };
        ServiceUpdate: {
            name?: string;
            kind?: string;
            /** Format: uri */
            endpoint?: string | null;
            enabled?: boolean;
        };
        /** @enum {string} */
        ServiceState: "operational" | "degraded" | "outage" | "maintenance" | "unknown";
        /** @enum {string} */
        Priority: "critical" | "warning" | "info" | "success";
        /** @enum {string} */
        AlertState: "open" | "acknowledged" | "resolved";
        Alert: {
            id: string;
            product_id?: string | null;
            service_id?: string | null;
            fingerprint: string;
            priority: components["schemas"]["Priority"];
            state: components["schemas"]["AlertState"];
            title: string;
            message: string;
            /** Format: date-time */
            opened_at: string;
            /** Format: date-time */
            acknowledged_at?: string | null;
            /** Format: date-time */
            resolved_at?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        AlertCreate: {
            product_id?: string | null;
            service_id?: string | null;
            fingerprint: string;
            priority: components["schemas"]["Priority"];
            title: string;
            message: string;
            /** Format: date-time */
            expires_at?: string | null;
        };
        Deployment: {
            id: string;
            product_id?: string | null;
            repository: string;
            branch: string;
            workflow: string;
            /** @enum {string} */
            status: "queued" | "in_progress" | "success" | "failure" | "cancelled";
            commit_sha: string;
            commit_message?: string;
            author: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: uri */
            html_url?: string | null;
        };
        MarketQuote: {
            provider: string;
            symbol: string;
            quote_asset: string;
            bid?: number | null;
            ask?: number | null;
            last: number;
            change_percent: number;
            /** Format: date-time */
            observed_at: string;
            /** @default false */
            stale: boolean;
        };
        Weather: {
            location: string;
            temperature_c: number;
            apparent_temperature_c: number;
            humidity_percent?: number;
            weather_code: number;
            wind_kmh?: number;
            daily_min_c?: number;
            daily_max_c?: number;
            precipitation_probability_percent?: number;
            /** Format: date-time */
            observed_at: string;
            /** @default false */
            stale: boolean;
        };
        DeviceCreate: {
            device_id: string;
            name: string;
            profile_id: string;
        };
        Device: {
            id: string;
            device_id: string;
            name: string;
            profile_id: string;
            /** @enum {string} */
            state: "online" | "offline" | "disabled" | "revoked";
            firmware_version?: string | null;
            /** Format: date-time */
            last_seen_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        DeviceUpdate: {
            name?: string;
            profile_id?: string;
            /** @enum {string} */
            state?: "offline" | "disabled";
            overrides?: {
                [key: string]: unknown;
            };
        };
        DeviceCredentials: {
            /** @description One-time value. */
            device_secret: string;
            mqtt_username: string;
            /** @description One-time value. */
            mqtt_password: string;
        };
        DeviceCreated: {
            device: components["schemas"]["Device"];
            /** @description One-time value. */
            device_secret: string;
            mqtt_username: string;
            /** @description One-time value. */
            mqtt_password: string;
        };
        ProfileScreen: {
            id: string;
            /** @enum {string} */
            type: "overview" | "product_status" | "service_status" | "alert" | "deployment" | "market" | "weather" | "metric_list" | "message";
            priority: number;
            duration_ms: number;
            enabled: boolean;
            config: {
                [key: string]: unknown;
            };
        };
        ScreenProfileWrite: {
            key: string;
            name: string;
            screens: components["schemas"]["ProfileScreen"][];
        };
        ScreenProfile: components["schemas"]["ScreenProfileWrite"] & {
            id: string;
            revision: number;
        };
        Setting: {
            namespace: string;
            key: string;
            value: unknown;
            /** @enum {string} */
            value_type: "string" | "integer" | "number" | "boolean" | "duration" | "object";
            revision: number;
            editable: boolean;
        };
        GitHubActionEvent: {
            product_key?: string;
            repository: string;
            branch: string;
            workflow: string;
            /** @enum {string} */
            status: "queued" | "in_progress" | "success" | "failure" | "cancelled";
            commit_sha: string;
            commit_message?: string;
            author: string;
            /** Format: date-time */
            occurred_at: string;
            /** Format: uri */
            html_url?: string;
        };
        UptimeEvent: {
            monitor: {
                id: number | string;
                name: string;
                url?: string | null;
            } | null;
            heartbeat: {
                /** @enum {integer} */
                status: 0 | 1;
                time: string;
                ping?: number | null;
                msg?: string | null;
            } | null;
            msg: string;
        };
        StreamEvent: {
            id: string;
            /** @enum {string} */
            type: "created" | "updated" | "deleted" | "invalidated";
            /** Format: date-time */
            occurred_at: string;
            /** @enum {string} */
            resource: "dashboard" | "product" | "service" | "alert" | "deployment" | "market" | "weather" | "device" | "profile" | "setting";
            resource_id?: string | null;
        };
        screenBase: {
            id: string;
            type: string;
            priority: number;
            duration_ms: number;
            title: string;
            payload: Record<string, never>;
        };
        /** @enum {unknown} */
        serviceState: "operational" | "degraded" | "outage" | "maintenance" | "unknown";
        overviewScreen: components["schemas"]["screenBase"] & {
            /** @constant */
            type?: "overview";
            payload?: {
                status: components["schemas"]["serviceState"];
                products: number;
                services: number;
                open_alerts: number;
                subtitle?: string;
            };
        };
        productScreen: components["schemas"]["screenBase"] & {
            /** @constant */
            type?: "product_status";
            payload?: {
                product_key: string;
                name: string;
                status: components["schemas"]["serviceState"];
                services_up: number;
                services_total: number;
                detail?: string;
            };
        };
        serviceScreen: components["schemas"]["screenBase"] & {
            /** @constant */
            type?: "service_status";
            payload?: {
                name: string;
                status: components["schemas"]["serviceState"];
                latency_ms?: number | null;
                /** Format: date-time */
                last_change_at?: string | null;
                detail?: string;
            };
        };
        /** @enum {unknown} */
        semanticPriority: "critical" | "warning" | "info" | "success";
        notificationStyle: {
            color: string;
            icon: string;
            led_rgb: string;
            /** @enum {string} */
            sound: "none" | "future_default";
        };
        alertScreen: components["schemas"]["screenBase"] & {
            /** @constant */
            type?: "alert";
            payload?: {
                alert_id: string;
                severity: components["schemas"]["semanticPriority"];
                message: string;
                source?: string;
                style: components["schemas"]["notificationStyle"];
            };
        };
        deploymentScreen: components["schemas"]["screenBase"] & {
            /** @constant */
            type?: "deployment";
            payload?: {
                repository: string;
                branch: string;
                workflow: string;
                /** @enum {unknown} */
                status: "queued" | "in_progress" | "success" | "failure" | "cancelled";
                commit_short: string;
                author: string;
                /** Format: date-time */
                occurred_at?: string;
            };
        };
        marketScreen: components["schemas"]["screenBase"] & {
            /** @constant */
            type?: "market";
            payload?: {
                symbol: string;
                display_value: string;
                bid?: string | null;
                ask?: string | null;
                change_percent: number;
                /** @enum {unknown} */
                trend: "up" | "down" | "flat";
                stale?: boolean;
            };
        };
        weatherScreen: components["schemas"]["screenBase"] & {
            /** @constant */
            type?: "weather";
            payload?: {
                location: string;
                temperature_c: number;
                apparent_temperature_c?: number;
                condition_icon: string;
                daily_min_c: number;
                daily_max_c: number;
                precipitation_probability_percent?: number;
                stale?: boolean;
            };
        };
        metricListScreen: components["schemas"]["screenBase"] & {
            /** @constant */
            type?: "metric_list";
            payload?: {
                items: {
                    label: string;
                    value: string;
                    /** @enum {unknown} */
                    trend?: "up" | "down" | "flat" | "none";
                    color?: string;
                }[];
            };
        };
        messageScreen: components["schemas"]["screenBase"] & {
            /** @constant */
            type?: "message";
            payload?: {
                message: string;
                style: components["schemas"]["notificationStyle"];
            };
        };
        screen: components["schemas"]["overviewScreen"] | components["schemas"]["productScreen"] | components["schemas"]["serviceScreen"] | components["schemas"]["alertScreen"] | components["schemas"]["deploymentScreen"] | components["schemas"]["marketScreen"] | components["schemas"]["weatherScreen"] | components["schemas"]["metricListScreen"] | components["schemas"]["messageScreen"];
        /** Device dashboard snapshot */
        "dashboard.schema": {
            /** @constant */
            schema_version: 1;
            revision: string;
            /** Format: date-time */
            generated_at: string;
            /** Format: date-time */
            expires_at: string;
            screens: components["schemas"]["screen"][];
            $defs: {
                screenBase: {
                    id: string;
                    type: string;
                    priority: number;
                    duration_ms: number;
                    title: string;
                    payload: Record<string, never>;
                };
                screen: components["schemas"]["overviewScreen"] | components["schemas"]["productScreen"] | components["schemas"]["serviceScreen"] | components["schemas"]["alertScreen"] | components["schemas"]["deploymentScreen"] | components["schemas"]["marketScreen"] | components["schemas"]["weatherScreen"] | components["schemas"]["metricListScreen"] | components["schemas"]["messageScreen"];
                overviewScreen: components["schemas"]["screenBase"] & {
                    /** @constant */
                    type?: "overview";
                    payload?: {
                        status: components["schemas"]["serviceState"];
                        products: number;
                        services: number;
                        open_alerts: number;
                        subtitle?: string;
                    };
                };
                productScreen: components["schemas"]["screenBase"] & {
                    /** @constant */
                    type?: "product_status";
                    payload?: {
                        product_key: string;
                        name: string;
                        status: components["schemas"]["serviceState"];
                        services_up: number;
                        services_total: number;
                        detail?: string;
                    };
                };
                serviceScreen: components["schemas"]["screenBase"] & {
                    /** @constant */
                    type?: "service_status";
                    payload?: {
                        name: string;
                        status: components["schemas"]["serviceState"];
                        latency_ms?: number | null;
                        /** Format: date-time */
                        last_change_at?: string | null;
                        detail?: string;
                    };
                };
                alertScreen: components["schemas"]["screenBase"] & {
                    /** @constant */
                    type?: "alert";
                    payload?: {
                        alert_id: string;
                        severity: components["schemas"]["semanticPriority"];
                        message: string;
                        source?: string;
                        style: components["schemas"]["notificationStyle"];
                    };
                };
                deploymentScreen: components["schemas"]["screenBase"] & {
                    /** @constant */
                    type?: "deployment";
                    payload?: {
                        repository: string;
                        branch: string;
                        workflow: string;
                        /** @enum {unknown} */
                        status: "queued" | "in_progress" | "success" | "failure" | "cancelled";
                        commit_short: string;
                        author: string;
                        /** Format: date-time */
                        occurred_at?: string;
                    };
                };
                marketScreen: components["schemas"]["screenBase"] & {
                    /** @constant */
                    type?: "market";
                    payload?: {
                        symbol: string;
                        display_value: string;
                        bid?: string | null;
                        ask?: string | null;
                        change_percent: number;
                        /** @enum {unknown} */
                        trend: "up" | "down" | "flat";
                        stale?: boolean;
                    };
                };
                weatherScreen: components["schemas"]["screenBase"] & {
                    /** @constant */
                    type?: "weather";
                    payload?: {
                        location: string;
                        temperature_c: number;
                        apparent_temperature_c?: number;
                        condition_icon: string;
                        daily_min_c: number;
                        daily_max_c: number;
                        precipitation_probability_percent?: number;
                        stale?: boolean;
                    };
                };
                metricListScreen: components["schemas"]["screenBase"] & {
                    /** @constant */
                    type?: "metric_list";
                    payload?: {
                        items: {
                            label: string;
                            value: string;
                            /** @enum {unknown} */
                            trend?: "up" | "down" | "flat" | "none";
                            color?: string;
                        }[];
                    };
                };
                messageScreen: components["schemas"]["screenBase"] & {
                    /** @constant */
                    type?: "message";
                    payload?: {
                        message: string;
                        style: components["schemas"]["notificationStyle"];
                    };
                };
                /** @enum {unknown} */
                serviceState: "operational" | "degraded" | "outage" | "maintenance" | "unknown";
                /** @enum {unknown} */
                semanticPriority: "critical" | "warning" | "info" | "success";
                notificationStyle: {
                    color: string;
                    icon: string;
                    led_rgb: string;
                    /** @enum {string} */
                    sound: "none" | "future_default";
                };
            };
        };
        /** Effective device configuration */
        "device-config.schema": {
            /** @constant */
            schema_version: 1;
            revision: string;
            /** @default America/Argentina/Cordoba */
            timezone: string;
            refresh_interval_seconds: number;
            display: {
                /** @constant */
                width: 172;
                /** @constant */
                height: 320;
                /** @enum {unknown} */
                orientation: "portrait" | "landscape" | "portrait_inverted" | "landscape_inverted";
                brightness_percent: number;
            };
            mqtt: {
                /** Format: uri */
                url: string;
                keep_alive_seconds: number;
                topics: {
                    alerts: string;
                    notifications: string;
                    commands: string;
                    status: string;
                    telemetry: string;
                    acks: string;
                    /** @constant */
                    global_events: "desk/global/events";
                };
            };
            notification_styles: {
                critical: components["schemas"]["notificationStyle"];
                warning: components["schemas"]["notificationStyle"];
                info: components["schemas"]["notificationStyle"];
                success: components["schemas"]["notificationStyle"];
            };
        };
    };
    responses: {
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Invalid request. */
        Problem400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated actor lacks permission. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description State or uniqueness conflict. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request rate exceeded. */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Required dependency unavailable. */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        IfNoneMatch: string;
        Cursor: string;
        Limit: number;
        ProductFilter: string;
        ProductId: string;
        ServiceId: string;
        AlertId: string;
        DeviceId: string;
        ProfileId: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Minimal public platform status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicHealth"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process and event loop are alive. Internal listener only. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicHealth"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Required dependencies are ready. Internal listener only. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build information. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Access token; refresh token is set as an HttpOnly cookie. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rotated session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    exchangeDeviceSecret: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceTokenRequest"];
            };
        };
        responses: {
            /** @description Short-lived device token and MQTT connection data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceTokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    getDeviceDashboard: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authoritative screen snapshot. */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["dashboard.schema"];
                };
            };
            /** @description Dashboard revision did not change. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDeviceConfig: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effective device configuration. */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["device-config.schema"];
                };
            };
            /** @description Configuration revision did not change. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listProducts: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items: components["schemas"]["Product"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductWrite"];
            };
        };
        responses: {
            /** @description Product created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product archived. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["ProductWrite"];
            };
        };
        responses: {
            /** @description Product updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listServices: {
        parameters: {
            query?: {
                product_id?: components["parameters"]["ProductFilter"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items: components["schemas"]["Service"][];
                    };
                };
            };
        };
    };
    createService: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceCreate"];
            };
        };
        responses: {
            /** @description Service created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceId: components["parameters"]["ServiceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceId: components["parameters"]["ServiceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service archived. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceId: components["parameters"]["ServiceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["ServiceUpdate"];
            };
        };
        responses: {
            /** @description Service updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                state?: components["schemas"]["AlertState"];
                priority?: components["schemas"]["Priority"];
                product_id?: components["parameters"]["ProductFilter"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items: components["schemas"]["Alert"][];
                    };
                };
            };
        };
    };
    createManualAlert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertCreate"];
            };
        };
        responses: {
            /** @description Manual alert created and queued for publication. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    acknowledgeAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alertId: components["parameters"]["AlertId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert acknowledged idempotently. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    resolveAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alertId: components["parameters"]["AlertId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert resolved idempotently. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listDeployments: {
        parameters: {
            query?: {
                product_id?: components["parameters"]["ProductFilter"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployment page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items: components["schemas"]["Deployment"][];
                    };
                };
            };
        };
    };
    listMarketQuotes: {
        parameters: {
            query?: {
                symbol?: string;
                from?: string;
                to?: string;
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quote history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items: components["schemas"]["MarketQuote"][];
                    };
                };
            };
        };
    };
    getWeather: {
        parameters: {
            query?: {
                location?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest weather observation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Weather"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Devices. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"][];
                };
            };
        };
    };
    createDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreate"];
            };
        };
        responses: {
            /** @description Device and one-time credentials. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCreated"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description REST and MQTT credentials revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["DeviceUpdate"];
            };
        };
        responses: {
            /** @description Device updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    rotateDeviceCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Previous credentials revoked and one-time replacements returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCredentials"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Screen profiles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenProfile"][];
                };
            };
        };
    };
    createProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenProfileWrite"];
            };
        };
        responses: {
            /** @description Profile created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenProfile"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Screen profile detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenProfile"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    replaceProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenProfileWrite"];
            };
        };
        responses: {
            /** @description Profile replaced and revision incremented. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenProfile"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unassigned profile deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Non-secret editable settings and their schemas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Setting"][];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Effective settings after validation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Setting"][];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    retryCollector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectorName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection scheduled idempotently. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    receiveGitHubWebhook: {
        parameters: {
            query?: never;
            header: {
                "X-GitHub-Event": string;
                "X-GitHub-Delivery": string;
                "X-Hub-Signature-256": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Valid delivery accepted or already processed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    receiveGitHubAction: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitHubActionEvent"];
            };
        };
        responses: {
            /** @description Event accepted or already processed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    receiveUptimeEvent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UptimeEvent"];
            };
        };
        responses: {
            /** @description Event accepted or already processed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE invalidation stream. Event data conforms to StreamEvent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
